/* INVOICES */
export const GET_INVOICES = "GET_INVOICES"
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS"
export const GET_INVOICES_FAIL = "GET_INVOICES_FAIL"

export const GET_INVOICE_DETAIL = "GET_INVOICE_DETAIL"
export const GET_INVOICE_DETAIL_SUCCESS = "GET_INVOICE_DETAIL_SUCCESS"
export const GET_INVOICE_DETAIL_FAIL = "GET_INVOICE_DETAIL_FAIL"
export const GET_ITEMMASTERS= "GET_ITEMMASTERS"

export const ADD_INVOICE='ADD_INVOICE'
export const ADD_INVOICE_SUCCESS = "ADD_INVOICE_SUCCESS"
export const ADD_INVOICE_FAIL = "ADD_INVOICE_FAIL"

export const DELETE_INVOICE = "DELETE_INVOICE"
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS"
export const EDIT_INVOICES = "EDIT_INVOICES"

export const EDIT_INVOICES_SUCCESS= "EDIT_INVOICES_SUCCESS"
export const ADD_INVOICE_STATE= "ADD_INVOICE_STATE"
export const CURRENT_INVOICE_STATE= "CURRENT_INVOICE_STATE"

export const RESET_EDIT_INVOICE_DATA= "RESET_EDIT_INVOICE_DATA"








