/* PAGES */
export const GET_PAGES = "GET_PAGES"
export const GET_PAGES_SUCCESS = "GET_PAGES_SUCCESS"
export const GET_PAGES_FAIL = "GET_PAGES_FAIL"

export const GET_PAGE_DETAIL = "GET_PAGE_DETAIL"
export const GET_PAGE_DETAIL_SUCCESS = "GET_PAGE_DETAIL_SUCCESS"
export const GET_PAGE_DETAIL_FAIL = "GET_PAGE_DETAIL_FAIL"
