  export const rollData =  [
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 2,
        CompanyID: 1,
        ModuleName: "Administration",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 26,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 21,
            RelatedPagePath: null,
            ActualPagePath: "../Administration/UserMasterList.aspx",
            PageName: "User List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 110,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Administration/HPageList.aspx",
            PageName: "Page List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 111,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Administration/RoleAccessMaster.aspx",
            PageName: "Role Access Master",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 112,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Administration/UserAccessMaster.aspx",
            PageName: "User Access Master",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 115,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 114,
            RelatedPagePath: null,
            ActualPagePath: "../Administration/GeneralMasterList.aspx",
            PageName: "General Master List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 135,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Administration/RoleAccessToDivision.aspx",
            PageName: "Copy Role Access",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 207,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Administration/TransactionPage.aspx",
            PageName: "Transaction Information",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 9,
        CompanyID: 1,
        ModuleName: "Sales",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 4,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 2,
            RelatedPagePath: null,
            ActualPagePath: "../Sales/OrderList.aspx?Mode=2",
            PageName: "Order List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 15,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 5,
            RelatedPagePath: null,
            ActualPagePath: "../Sales/InvoiceList.aspx",
            PageName: "Invoice List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 18,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 14,
            RelatedPagePath: null,
            ActualPagePath: "../Sales/ItemRateList.aspx",
            PageName: "Rate List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 198,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 147,
            RelatedPagePath: null,
            ActualPagePath: "../Sales/SaleReturnList.aspx?Mode=3",
            PageName: "Sale Return Credit",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 199,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 147,
            RelatedPagePath: null,
            ActualPagePath: "../Sales/SaleReturnList.aspx?Mode=2",
            PageName: "Sale Return Accept",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 5,
        CompanyID: 1,
        ModuleName: "Purchase",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 280,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 196,
            RelatedPagePath: null,
            ActualPagePath: "../Purchase/PurchaseReturnList.aspx",
            PageName: "Purchase Return List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 6,
        CompanyID: 1,
        ModuleName: "Inter Branch",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 49,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../InterBranch/IBDemand.aspx",
            PageName: "Demand",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 51,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 49,
            RelatedPagePath: null,
            ActualPagePath: "../InterBranch/IBDemandList.aspx?Mode=1",
            PageName: "Demand List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 55,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 49,
            RelatedPagePath: null,
            ActualPagePath: "../InterBranch/IBDemandList.aspx?Mode=2",
            PageName: "Demand Order List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 58,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 96,
            RelatedPagePath: null,
            ActualPagePath: "../InterBranch/IBChallanList.aspx?Mode=1",
            PageName: "Challan List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 59,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 96,
            RelatedPagePath: null,
            ActualPagePath: "../InterBranch/IBChallanList.aspx?Mode=2",
            PageName: "Inward",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 68,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 97,
            RelatedPagePath: null,
            ActualPagePath: "../InterBranch/IBInwardList.aspx",
            PageName: "Inward List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 151,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../InterBranch/IBManualInward.aspx",
            PageName: "Manual Inward",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 7,
        CompanyID: 1,
        ModuleName: "Inventory",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 20,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 6,
            RelatedPagePath: null,
            ActualPagePath: "../Inventory/StockInwardList.aspx",
            PageName: "GRN List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 48,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Inventory/StockEntry.aspx?Mode=1",
            PageName: "Stock Entry",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 60,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Inventory/StockEntry.aspx?Mode=2",
            PageName: "Stock Adjustment",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 116,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Inventory/StockInward.aspx?Mode=2",
            PageName: "GRN (QR Code)",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 289,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Inventory/GRNBySupplier.aspx",
            PageName: "New GRN ",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 11,
        CompanyID: 1,
        ModuleName: "Accounting",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 46,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 45,
            RelatedPagePath: null,
            ActualPagePath: "../Accounts/ReceiptMasterList.aspx",
            PageName: "Receipts List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 106,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 105,
            RelatedPagePath: null,
            ActualPagePath: "../Accounts/AccountList.aspx",
            PageName: "Accounts List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 131,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 130,
            RelatedPagePath: null,
            ActualPagePath: "../Accounts/DebitCreditNoteList.aspx",
            PageName: "Debit Credit Note List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 153,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Accounts/ReceiptMaster.aspx?Mode=2",
            PageName: "Credit Note",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 338,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 336,
            RelatedPagePath: null,
            ActualPagePath: "../Accounts/CreditReturnListGST.aspx",
            PageName: "GST CreditNote List [Invoice]",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 15,
        CompanyID: 1,
        ModuleName: "Master",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 8,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 7,
            RelatedPagePath: null,
            ActualPagePath: "../Master/ItemGroupList.aspx",
            PageName: "Item Group List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 10,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 9,
            RelatedPagePath: null,
            ActualPagePath: "../Master/ItemMasterList.aspx",
            PageName: "Central Item  List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 12,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 11,
            RelatedPagePath: null,
            ActualPagePath: "../Master/LocalItemMasterList.aspx",
            PageName: "Item  List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 34,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 33,
            RelatedPagePath: null,
            ActualPagePath: "../Master/PartyTypesMasterList.aspx",
            PageName: "Party Type List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 36,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 35,
            RelatedPagePath: null,
            ActualPagePath: "../Master/ManagementUsersList.aspx",
            PageName: "Management User List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 38,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 37,
            RelatedPagePath: null,
            ActualPagePath: "../Master/VehicleMasterList.aspx",
            PageName: "Vehicle List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 41,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Master/SupplierItemCodeMaster.aspx",
            PageName: "Supplier Item Code",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 42,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Master/ItemSupplierMaster.aspx",
            PageName: "Item Supplier Master",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 43,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Master/ItemDivisions.aspx",
            PageName: "Item Division",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 118,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 117,
            RelatedPagePath: null,
            ActualPagePath: "../Master/PartiesMasterList.aspx",
            PageName: "Parties Master List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 124,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 123,
            RelatedPagePath: null,
            ActualPagePath: "../Master/PartySubTypeMasterList.aspx",
            PageName: "PartySubType List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 149,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Master/ItemsGroups.aspx",
            PageName: "Items Groups",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 158,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Master/CustomerCreditLimit.aspx",
            PageName: "Customer Credit Limit",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 321,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Master/BankMaster.aspx",
            PageName: "Bank Master",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 322,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 321,
            RelatedPagePath: null,
            ActualPagePath: "../Master/BankMasterList.aspx",
            PageName: "Bank  Master List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 352,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 351,
            RelatedPagePath: null,
            ActualPagePath: "../Master/SchemeItemMasterList.aspx",
            PageName: "Scheme Item List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 383,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Master/EwayBillDistance.aspx",
            PageName: "Eway Bill Distance",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 4,
        CompanyID: 1,
        ModuleName: "HR",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 30,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 29,
            RelatedPagePath: null,
            ActualPagePath: "../HR/DesignationMasterList.aspx",
            PageName: "Designation  List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 32,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 31,
            RelatedPagePath: null,
            ActualPagePath: "../HR/EmployeeMasterList.aspx",
            PageName: "Employee List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 16,
        CompanyID: 1,
        ModuleName: "Reports",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 50,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Wholesale/FranchiseReportMaster.aspx",
            PageName: "Franchise Orders",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 61,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=5",
            PageName: "Stock Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 63,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=4",
            PageName: "Challan Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 66,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=1",
            PageName: "Supplier Demands",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 98,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=6",
            PageName: "Item Sale Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 102,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=8",
            PageName: "Party Ledger",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 103,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=9",
            PageName: "Partywise Total Sales",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 104,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=10",
            PageName: "Partywise Receipts",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 125,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=12",
            PageName: "Periodic Cheque List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 126,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=11",
            PageName: "Meterial Register",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 127,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=16",
            PageName: "Invoice Summary",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 129,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=18",
            PageName: "Daily Bills & Receipts",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 137,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=22",
            PageName: "Demand vs Supply",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 150,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=25",
            PageName: "All Party Sales",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 152,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=23",
            PageName: "Rate List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 157,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=14",
            PageName: "Inward Item Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 168,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "\t../Reports/BaseReportPage.aspx?Mode=27",
            PageName: "OutStanding Balance",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 170,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=28",
            PageName: "Annual Item Sale Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 172,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=29",
            PageName: "Multiple Items Sale",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 174,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=30",
            PageName: "Festiv Order Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 206,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=35",
            PageName: "Date Wise Period Stock",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 224,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=33",
            PageName: "Employee Wise Attendance Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 229,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=15",
            PageName: "Daily Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 272,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=60",
            PageName: "Sales Annexure",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 307,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=84",
            PageName: "Daily Attendance Report",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 328,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=90",
            PageName: "GST Item wise Sale",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 345,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=101",
            PageName: "Multiple Item Qty Amt",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 385,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Reports/BaseReportPage.aspx?Mode=129",
            PageName: "Franchises POS Summary",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 19,
        CompanyID: 1,
        ModuleName: "Payroll",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 201,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/Attendance.aspx",
            PageName: "Employee Attendance",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 209,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/SalaryDeduction.aspx?Mode=1",
            PageName: "Salary Allowance",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 210,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/SalaryDeduction.aspx?Mode=2",
            PageName: "Salary Deduction",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 211,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/SalaryProcess.aspx",
            PageName: "Salary Process",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 213,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 212,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/MonthlyAttendanceList.aspx",
            PageName: "Monthly Attendance",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 216,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 215,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/AllowanceDeductionList.aspx?Mode=1",
            PageName: "Allowance List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 218,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 217,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/AllowanceDeductionList.aspx?Mode=2",
            PageName: "Deduction List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 220,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 219,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/PaymentDetailsList.aspx",
            PageName: "Payment Detail List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 222,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 221,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/AnnualHolidayList.aspx",
            PageName: "Annual Holiday List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 223,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../Payroll/DailyAttendance.aspx",
            PageName: "Daily Attendance",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 20,
        CompanyID: 1,
        ModuleName: "Deposit",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 242,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 241,
            RelatedPagePath: null,
            ActualPagePath: "../DepositModule/WholesalerMasterList.aspx?Mode=1",
            PageName: "Customer List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 244,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 243,
            RelatedPagePath: null,
            ActualPagePath: "../DepositModule/DepositMasterList.aspx?Mode=3",
            PageName: "Deposit List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 251,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 250,
            RelatedPagePath: null,
            ActualPagePath: "../DepositModule/DepositMasterList.aspx?Mode=1",
            PageName: "Refund List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 252,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../DepositModule/DepositMasterList.aspx?Mode=5",
            PageName: "Deposit Ledger",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      },
      {
        ID: 0,
        RoleID: 3,
        DivisionID: 3,
        ModuleID: 21,
        CompanyID: 1,
        ModuleName: "Deposit 2",
        DisplayIndex: 0,
        RoleAccessList: [
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 313,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 312,
            RelatedPagePath: null,
            ActualPagePath: "../DepositModule/WholesalerMasterList.aspx?Mode=2",
            PageName: "Customer List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 315,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 314,
            RelatedPagePath: null,
            ActualPagePath: "../DepositModule/DepositMasterList.aspx?Mode=4",
            PageName: "Deposit List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 317,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 316,
            RelatedPagePath: null,
            ActualPagePath: "../DepositModule/DepositMasterList.aspx?Mode=2",
            PageName: "Refund List",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          },
          {
            ID: 0,
            RoleID: 0,
            DivisionID: 0,
            ModuleID: 0,
            ModuleName: null,
            SubModuleID: 0,
            SubModuleName: null,
            PageID: 319,
            IsShow: false,
            IsShowAddPage: false,
            IsAdd: false,
            IsEditSelf: false,
            IsEdit: false,
            IsView: false,
            IsDeleteSelf: false,
            IsDelete: false,
            IsPrint: false,
            CompanyID: 0,
            RelatedPageID: 0,
            RelatedPagePath: null,
            ActualPagePath: "../DepositModule/DepositMasterList.aspx?Mode=6",
            PageName: "Deposit Ledger(Deposit 2)",
            SubModuleDisplayIndex: 0,
            ModuleDisplayIndex: 0,
            PageAttributes: null,
            Name: null
          }
        ]
      }
    ]
  